version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                user: laravel
                uid: 1000
        image: esencia-seguros-api
        container_name: esencia-seguros-app
        restart: unless-stopped
        tty: true
        working_dir: /var/www
        volumes:
            - .:/var/www
            - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
        networks:
            - esencia-network
        depends_on:
            - mysql
            - phpmyadmin

    mysql:
        image: mysql:8.0
        container_name: esencia-seguros-mysql
        restart: unless-stopped
        tty: true
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: esencia_seguros
            MYSQL_USER: esencia_user
            MYSQL_PASSWORD: esencia_password_2024
            MYSQL_ROOT_PASSWORD: esencia_root_2024
        volumes:
            - ./docker/mysql:/var/lib/mysql
        networks:
            - esencia-network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: esencia-seguros-phpmyadmin
        restart: unless-stopped
        tty: true
        ports:
            - "8081:80"
        environment:
            PMA_HOST: mysql
            PMA_USER: root
            PMA_PASSWORD: esencia_root_2024
        depends_on:
            - mysql
        networks:
            - esencia-network
    nginx:
        image: nginx:stable-alpine
        container_name: esencia-seguros-nginx
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - esencia-network


networks:
    esencia-network:
        driver: bridge
